apiVersion: v1
kind: Namespace
metadata:
  name: locust
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: locust
  labels:
    name: locust-master
spec:
  replicas: ${locust_master_replicas}
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: kezhenxu94/oap-load-test-locust:1.0.0
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              value: http://service0.test:9999
            - name: LOCUST_USERS
              value: "${locust_users}"
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: locust
  labels:
    name: locust-worker
spec:
  replicas: ${locust_worker_replicas}
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: kezhenxu94/oap-load-test-locust:1.0.0
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: http://service0.test:9999
---
kind: Service
apiVersion: v1
metadata:
  name: locust-master
  namespace: locust
  labels:
    app: locust-master
spec:
  ports:
    - port: 8089
      targetPort: loc-master-web
      protocol: TCP
      name: loc-master-web
    - port: 5557
      targetPort: loc-master-p1
      protocol: TCP
      name: loc-master-p1
    - port: 5558
      targetPort: loc-master-p2
      protocol: TCP
      name: loc-master-p2
  selector:
    app: locust-master
  type: LoadBalancer
