apiVersion: v1
kind: ConfigMap
metadata:
  name: ${configmap_name}
  namespace: ${namespace}
data:
  nginx.conf: |
    user nginx;
    worker_processes  auto;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen       9999;
        server_name  0.0.0.0;
        access_log off;
        location / {
          return 200 '';
          add_header Content-Type text/plain;
        }
      }
    }
