apiVersion: v1
kind: Service
metadata:
  name: ${service_name}
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: ${service_name}
